controller_list:
  - name: /motoman_gp8/gp8_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: [joint_1_s, joint_2_l, joint_3_u, joint_4_r, joint_5_b, joint_6_t]